package com.symlab.dandelion;

public interface Constants { 
	//
	int NETWORK_PING = 1;
	int NETWORK_PONG = 2;
	int NETWORK_REQUEST_STATUS = 3;
	int NETWORK_RUN_TASK = 4;
	int NETWORK_APK_REGISTER = 5;
	int NETWORK_APK_PRESENT = 6;
	int NETWORK_APK_REQUEST = 7;
	int NETWORK_TASK_RESULT = 8;
	int NETWORK_CLOSE = 10;
	int NETWORK_CONNECTING = 9;
	int NETWORK_READY = 10;
	
	
	int TO_SERVICE_REGISTER = 101;
	int TO_SERVICE_DISCOVER = 102;
	int TO_SERVICE_NSDLIST_REQUEST = 103;
	
	int TO_CLIENT_NSDLIST_RESPONSE = 201;
	
	int PROFILER_UPDATE_PERIOD = 1000;
	
	int SERVER_PORT = 54321;
}
